#!/data/data/com.zdroid/files/usr/bin/sh
# Auto-generated by gpui_android termux_bootstrap. For each ELF in
# $PREFIX/bin/* symlinks (resolved into node_modules) and any deep
# ELF under $PREFIX/lib/node_modules/**:
#   1. patchelf musl interp /lib/ld-musl-aarch64.so.1 ->
#      $PREFIX/lib/ld-musl-aarch64.so.1 so the kernel can find the
#      linker (Android has no /lib).
#   2. hex-patch the rodata literal /etc/resolv.conf to
#      /sdcard/.zed/r (14 bytes + 2 NUL pad fits the 16-byte slot).
#      gpui_android::dns_bridge populates /sdcard/.zed/r at boot
#      with Android's active DNS servers.
#   3. for glibc-dynamic targets, write a grun-prefixed launcher
#      at the npm symlink path (or a stub if grun isn't installed).
# Patched binaries do outbound UDP DNS to the nameserver in
# /sdcard/.zed/r — no proot wrap, no ptrace overhead, no
# telemetry-storm amplification. Idempotent: rerunning is free.
set -u
PREFIX=/data/data/com.zdroid/files/usr
[ -d "$PREFIX/bin" ] || exit 0
[ -d "$PREFIX/lib/node_modules" ] || exit 0
[ -x "$PREFIX/bin/readelf" ] || exit 0

write_if_changed() {
    dst="$1"; want="$2"
    if [ -f "$dst" ] && [ "$(cat -- "$dst" 2>/dev/null)" = "$want" ]; then
        return 0
    fi
    rm -f -- "$dst"
    printf '%s\n' "$want" > "$dst"
    chmod +x -- "$dst"
}

# Locate patchelf with the same fallback the apt patchelf hook
# uses — prefer $PREFIX/bin/patchelf (the standard location),
# fall back to $PREFIX/glibc/bin/patchelf (the glibc-stack
# variant from `pkg install patchelf-glibc` or our manual
# symlink dance). Without this fallback, a user who lost
# $PREFIX/bin/patchelf (apt autoremove edge case, or hasn't
# installed it yet) gets silent no-ops here — the npm install
# appears to succeed but the resulting Bun-compiled binary
# has the unpatched /lib/ld-musl-aarch64.so.1 INTERP and
# fails at execve with `cannot execute: required file not
# found`.
PATCHELF=""
if [ -x "$PREFIX/bin/patchelf" ]; then PATCHELF="$PREFIX/bin/patchelf"; elif [ -x "$PREFIX/glibc/bin/patchelf" ]; then PATCHELF="$PREFIX/glibc/bin/patchelf"; fi
patch_musl_interp() {
    bin="$1"
    [ -n "$PATCHELF" ] || return 0
    interp=$("$PREFIX/bin/readelf" -l "$bin" 2>/dev/null | awk '/interpreter:/ { gsub(/[\[\]]/, "", $NF); print $NF; exit }')
    case "$interp" in
        /lib/ld-musl-aarch64.so.1)
            "$PATCHELF" --set-interpreter "$PREFIX/lib/ld-musl-aarch64.so.1" "$bin" 2>/dev/null || true
            "$PATCHELF" --set-rpath "$PREFIX/lib" "$bin" 2>/dev/null || true
            ;;
    esac
}

# Hex-patch /etc/resolv.conf -> /sdcard/.zed/r in the binary's
# .rodata. /etc/resolv.conf is 16 bytes; /sdcard/.zed/r is 14 +
# 2 NUL pad = 16, same width. c-ares opens via strlen so the NULs
# don't matter at the syscall layer. Bun-compiled CLIs whose
# static-musl libc bypasses LD_PRELOAD now read our DNS file
# instead of the missing /etc/resolv.conf — proot wrap dropped.
patch_resolv_conf() {
    bin="$1"
    [ -x "$PREFIX/bin/perl" ] || return 0
    grep -q -a -- '/etc/resolv.conf' "$bin" 2>/dev/null || return 0
    "$PREFIX/bin/perl" -e '
                my $path = $ARGV[0];
                open my $fh, "+<:raw", $path or exit 0;
                my $data = do { local $/; <$fh> };
                my $count = 0;
                while ($data =~ /\x00\/etc\/resolv\.conf\x00/g) {
                    my $offset = $-[0] + 1;
                    seek $fh, $offset, 0;
                    print $fh "/sdcard/.zed/r\x00\x00";
                    $count++;
                }
                close $fh;
                print STDERR "zed-launcher-gen: hex-patched $count /etc/resolv.conf in $path\n" if $count > 0;
            ' "$bin" 2>&1
}

handle_elf() {
    bin="$1"
    # Skip shell wrappers (ours from a previous run, or otherwise).
    head -c 2 -- "$bin" 2>/dev/null | grep -q '#!' && return 0
    # Skip non-ELF (JSON, .so without exec bit, etc.).
    "$PREFIX/bin/readelf" -h "$bin" >/dev/null 2>&1 || return 0
    patch_musl_interp "$bin"
    patch_resolv_conf "$bin"
    # For musl-static binaries: write a tiny wrapper at
    # $PREFIX/bin/<basename> that strips LD_PRELOAD before exec.
    # Reason: lib.rs sets LD_PRELOAD=libtermux-exec.so for the
    # whole process tree (bash/Node/etc inherit it for shebang
    # path-rewriting on com.termux paths). libtermux-exec is
    # bionic-linked; loading it into a musl process fails on
    # __system_property_get, __register_atfork, FORTIFY _chk
    # symbols that musl doesn't provide. The wrapper invokes the
    # patched binary directly (skipping any JS dispatcher) so
    # the env strip applies to the musl process from its first
    # exec — same shape as the old proot wrapper had `env -u
    # LD_PRELOAD` for the same reason, just minus the proot.
    interp=$("$PREFIX/bin/readelf" -l "$bin" 2>/dev/null | awk '/interpreter:/ { gsub(/[\[\]]/, "", $NF); print $NF; exit }')
    case "$interp" in
        "$PREFIX/lib/ld-musl-aarch64.so.1")
            name=$(basename -- "$bin")
            want="#!$PREFIX/bin/sh
exec env -u LD_PRELOAD \"$bin\" \"\$@\""
            write_if_changed "$PREFIX/bin/$name" "$want"
            ;;
    esac
}

handle_link() {
    link="$1"
    target=$(readlink -f -- "$link" 2>/dev/null)
    [ -n "$target" ] && [ -f "$target" ] || return 0
    case "$target" in
        "$PREFIX"/lib/node_modules/*) ;;
        *) return 0 ;;
    esac
    handle_elf "$target"
    # Glibc-dynamic targets need a wrapper through grun (or a
    # stub if grun isn't installed). musl/static targets are
    # already in-place patched above; npm's symlink invokes them
    # directly, kernel reads the patched ELF, c-ares reads
    # /sdcard/.zed/r, no extra wrapper needed.
    interp=$("$PREFIX/bin/readelf" -l "$target" 2>/dev/null | awk '/interpreter:/ { gsub(/[\[\]]/, "", $NF); print $NF; exit }')
    case "$interp" in
        */ld-linux-*)
            name=$(basename -- "$link")
            if [ -x "$PREFIX/bin/grun" ]; then
                want="#!$PREFIX/bin/sh
exec \"$PREFIX/bin/grun\" \"$target\" \"\$@\""
            else
                want="#!$PREFIX/bin/sh
echo \"error: $name needs glibc-runner. Install via:\" >&2
echo \"  pkg install tur-repo && pkg install glibc-runner\" >&2
exit 1"
            fi
            write_if_changed "$link" "$want"
            ;;
    esac
}

for link in "$PREFIX"/bin/*; do
    [ -L "$link" ] || continue
    handle_link "$link"
done

find "$PREFIX/lib/node_modules" -type f -perm -u+x \
             ! -name '*.js' ! -name '*.cjs' ! -name '*.mjs' ! -name '*.json' \
             ! -name 'node' ! -name 'corepack' \
             ! -name '*.real' \
             2>/dev/null | while IFS= read -r bin; do
    handle_elf "$bin"
done
exit 0
