#!/data/data/com.zdroid/files/usr/bin/sh
# Auto-generated by gpui_android termux_bootstrap. Runs after
# every dpkg --unpack on freshly-installed binaries:
#   1. patchelf DT_RUNPATH -> $PREFIX/lib (Termux's CI bakes
#      /data/data/com.termux/files/usr/lib into every ELF).
#   2. hex-patch /data/data/com.termux/ -> /data/data/com.zdroid/
#      in rodata. Same 22-byte length so rewrite is in-place;
#      closes the layer-3 in-binary string-constant gap that
#      used to need LD_PRELOAD shims or per-package wrappers.
#      Idempotent — the needle is gone after run 1.
# Without these, the dynamic linker either can't resolve shared
# libs (RUNPATH) or the binary fails at first runtime path open
# (rodata).
#
# Critical correctness invariants (learned the hard way):
# 1. NO --force-rpath. It converts DT_RUNPATH->DT_RPATH and on
#    some libs (e.g. libandroid-support.so) corrupts the file
#    by truncating its dynamic section.
# 2. Skip files whose RUNPATH already matches our prefix.
#    Bootstrap libs (built on Vultr) are pre-correct; touching
#    them risks the same patchelf section-layout issues.
# 3. `-cmin -1` (status change time, NOT mtime). dpkg preserves
#    the .deb's mtime (typically the build time) when extracting,
#    so `-mmin` would skip just-installed files. ctime updates
#    when dpkg chmods/chowns the file post-extract, so it's
#    reliably "recent" for newly-installed files.
# 4. Hex-pattern length must equal substitute length, or it'd
#    shift every byte after the match (PT_LOAD/section table
#    offsets break, ELF unloadable). The com.zdroid applicationId
#    is precisely 10 chars to satisfy this against com.termux.
set -u
PREFIX=/data/data/com.zdroid/files/usr
WANT="$PREFIX/lib"
# Locate patchelf — prefer $PREFIX/bin/patchelf (musl, matches our
# rest of the bootstrap), fall back to $PREFIX/glibc/bin/patchelf
# (glibc-stack package install). Falls through cleanly if neither
# is present — hex-patch path runs unconditionally below.
PATCHELF=""
if [ -x "$PREFIX/bin/patchelf" ]; then PATCHELF="$PREFIX/bin/patchelf"; elif [ -x "$PREFIX/glibc/bin/patchelf" ]; then PATCHELF="$PREFIX/glibc/bin/patchelf"; fi
maybe_patchelf() {
    [ -n "$PATCHELF" ] || return 0
    # Skip files we ship pristine — patchelf grows them by tens
    # of KB to add RPATH sections, which (a) is meaningless for
    # ld-musl-aarch64.so.1 (the dynamic linker doesn't read its
    # own RPATH) and (b) shifts section table offsets in
    # libc++_shared.so in ways that break apt's libstdc++ chain
    # on the next dpkg invocation. The dpkg.cfg.d/zed-protect-
    # libs path-exclude prevents the libc++ package from
    # overwriting libc++_shared.so; this skip-list is
    # defense-in-depth against patchelf rewriting it after a
    # cmin-recent ctime bump.
    case "${1##*/}" in
        ld-musl-aarch64.so.1|libc.musl-aarch64.so.1|libc++_shared.so) return 0 ;;
    esac
    current=$("$PATCHELF" --print-rpath "$1" 2>/dev/null) || return 0
    [ "$current" = "$WANT" ] && return 0
    # If hex-patch already fixed the RUNPATH (com.zdroid present),
    # leave it alone — for glibc-stack libs the correct RUNPATH
    # is $PREFIX/glibc/lib, NOT $PREFIX/lib, and patchelf would
    # overwrite the hex-patch's correct value with the musl-stack
    # path. Hex-patch handled this binary; trust it.
    case "$current" in *com.zdroid*) return 0 ;; esac
    "$PATCHELF" --set-rpath "$WANT" "$1" 2>/dev/null || true
}
maybe_hex_patch() {
    [ -x "$PREFIX/bin/perl" ] || return 0
    # Rewrite paths only present in binaries that actually have
    # something to rewrite. grep -q -a treats binary input as text
    # and short-circuits per pattern.
    local has_termux=0 has_resolv=0
    grep -q -a -- '/data/data/com.termux/' "$1" 2>/dev/null && has_termux=1
    grep -q -a -- '/etc/resolv.conf' "$1" 2>/dev/null && has_resolv=1
    [ $has_termux -eq 0 ] && [ $has_resolv -eq 0 ] && return 0
    "$PREFIX/bin/perl" -e '
                my $path = $ARGV[0];
                open my $fh, "+<:raw", $path or exit 0;
                my $data = do { local $/; <$fh> };
                my $tcount = 0;
                my $rcount = 0;
                # Pass 1: com.termux/ -> com.zdroid/ (22 bytes <-> 22 bytes,
                # in-place; the equal-length property of the com.zdroid
                # rename).
                while ($data =~ m{/data/data/com\.termux/}g) {
                    my $offset = $-[0];
                    seek $fh, $offset, 0;
                    print $fh "/data/data/com.zdroid/";
                    $tcount++;
                }
                # Pass 2: /etc/resolv.conf -> /sdcard/.zed/r + 2 NUL pad
                # (16 bytes <-> 14 + 2 NUL = 16). Anchored on leading and
                # trailing NUL to avoid matching false positives in
                # arbitrary string streams. dns_bridge.rs writes the
                # active-network nameservers to /sdcard/.zed/r at boot;
                # post-rewrite the binary opens that file instead of the
                # nonexistent Android /etc/resolv.conf and Go pure-Go
                # resolver / musl-libc resolver / c-ares all read it.
                while ($data =~ m{/etc/resolv\.conf}g) {
                    my $offset = $-[0];
                    seek $fh, $offset, 0;
                    print $fh "/sdcard/.zed/r\x00\x00";
                    $rcount++;
                }
                close $fh;
                print STDERR "zed-rodata-hex: $tcount com.termux, $rcount /etc/resolv.conf in $path\n" if ($tcount > 0 || $rcount > 0);
            ' "$1" 2>&1
}
find "$PREFIX/bin" "$PREFIX/sbin" "$PREFIX/libexec" "$PREFIX/glibc/bin" "$PREFIX/glibc/sbin" "$PREFIX/glibc/libexec" -type f -cmin -10 2>/dev/null | while IFS= read -r f; do maybe_hex_patch "$f"; maybe_patchelf "$f"; done
find "$PREFIX/lib" "$PREFIX/glibc/lib" -type f -cmin -10 -name '*.so*' 2>/dev/null | while IFS= read -r f; do maybe_hex_patch "$f"; maybe_patchelf "$f"; done
exit 0
